In [1]:
import pandas as pd
df=pd.read_csv('course_data_clean.csv')
df.head()

,course_code,course_title,num_ratings,useful,easy,liked,num_reviews,reviews,course_rating,course_rating_int
0,CS 115,Introduction to Computer Science 1,2111,21%,10%,23%,86,go to office hours and practice,liked course,1.0
1,CS 115,Introduction to Computer Science 1,2111,21%,10%,23%,86,One of my least favourite courses. Although th...,disliked course,0.0
2,CS 115,Introduction to Computer Science 1,2111,21%,10%,23%,86,It starts with a very low pace but after midte...,disliked course,0.0
3,CS 115,Introduction to Computer Science 1,2111,21%,10%,23%,86,Took this in 2018 with no programming experien...,liked course,1.0
4,CS 115,Introduction to Computer Science 1,2111,21%,10%,23%,86,I loved everything about cs 115. Great instruc...,liked course,1.0

In [31]:
pattern = '[0-9]'
df[df['course_title'].str.contains(pattern)]
df[df['course_title'].str.contains("Computer", case=False, na=False)]
df[df['course_title'].str.startswith("Intro")]
df[df['course_code'].isin(["CS 115"])]

,course_code,course_title,num_ratings,useful,easy,liked,num_reviews,reviews,course_rating,course_rating_int
0,CS 115,Introduction to Computer Science 1,2111,21%,10%,23%,86,go to office hours and practice,liked course,1.0
1,CS 115,Introduction to Computer Science 1,2111,21%,10%,23%,86,One of my least favourite courses. Although th...,disliked course,0.0
2,CS 115,Introduction to Computer Science 1,2111,21%,10%,23%,86,It starts with a very low pace but after midte...,disliked course,0.0
3,CS 115,Introduction to Computer Science 1,2111,21%,10%,23%,86,Took this in 2018 with no programming experien...,liked course,1.0
4,CS 115,Introduction to Computer Science 1,2111,21%,10%,23%,86,I loved everything about cs 115. Great instruc...,liked course,1.0
...,...,...,...,...,...,...,...,...,...,...
14753,KOREA 301R,Third-Year Korean 1,1,100%,100%,100%,1,it was super fun + engaging. I loved every lec...,liked course,1.0
14772,PHYS 701,Quantum Mechanics 1,1,100%,75%,100%,1,"Good course, well structured",liked course,1.0
14798,SI 250R,The History of Islamic Civilization from Late ...,1,100%,75%,100%,1,I took this course online and it consisted of ...,liked course,1.0
14799,SI 251R,The History of Islamic Civilization from 1300-...,1,0%,100%,100%,1,Prof seemed to be novice and said some histori...,liked course,1.0
14833,ASL 102R,American Sign Language 2,1,100%,75%,100%,1,Took this online with Georgia Whalen. As it wa...,liked course,1.0

In [4]:
df.shape

(14838, 10)